import { readFileSync, writeFileSync, chmodSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const __dirname = fileURLToPath(new URL(".", import.meta.url));
import { exec, execSync } from "node:child_process";
const execAsync = promisify(exec);
import { promisify } from "node:util";
import { defineConfig } from "@rspack/cli";
import {
  rspack,
  type ExternalsType,
  type ExternalItemFunctionData,
  type ExternalItemValue,
  type Mode,
  type RspackOptions,
  type Compilation,
  type WebpackCompiler,
} from "@rspack/core";
import { RsdoctorRspackPlugin } from "@rsdoctor/rspack-plugin";
import { TsCheckerRspackPlugin } from "ts-checker-rspack-plugin";
if (!process.env.CI) {
  try {
    writeFileSync(
      ".git/hooks/pre-commit",
      "pnpm format\ngit update-index --again",
    );
    chmodSync(".git/hooks/pre-commit", 0o755);
  } catch {}
}

function nodeExternals(
  { context, request }: ExternalItemFunctionData,
  callback: (
    err?: Error,
    result?: ExternalItemValue,
    type?: ExternalsType,
  ) => void,
) {
  if (!/^(\.|\/)/.test(request || "")) {
    return callback(undefined, request);
  }

  callback();
}

function extractRuntimeExportNames(source: string): string[] {
  const names = new Set<string>();

  // ESM bundles end with `export { __webpack_exports__X as X, ... };`
  const esmMatches = source.matchAll(/export\s*\{([^}]+)\}\s*;/g);
  for (const m of esmMatches) {
    for (const part of m[1].split(",")) {
      const trimmed = part.trim();
      if (!trimmed) continue;
      const asMatch = trimmed.match(/\s+as\s+([A-Za-z_$][\w$]*)\s*$/);
      const name = asMatch
        ? asMatch[1]
        : trimmed.match(/^([A-Za-z_$][\w$]*)/)?.[1];
      if (name) names.add(name);
    }
  }
  if (names.size > 0) return [...names];

  // Webpack IIFE bundles register entry exports via the *last*
  // `__webpack_require__.d(__webpack_exports__, { ... })` call. In
  // production builds those identifiers get minified (e.g. `r.d(o, {...})`),
  // so match any `<ident>.d(<ident>, { ... })` shape.
  const defMatches = [
    ...source.matchAll(
      /\b[A-Za-z_$][\w$]*\.d\([A-Za-z_$][\w$]*,\s*\{([\s\S]*?)\}\)/g,
    ),
  ];
  if (defMatches.length > 0) {
    const last = defMatches[defMatches.length - 1][1];
    for (const m of last.matchAll(/([A-Za-z_$][\w$]*)\s*:/g)) {
      names.add(m[1]);
    }
  }
  return [...names];
}

function renderExternalStub(names: string[], globalName: string): string {
  const sorted = [...names].sort();
  return [
    "// AUTO-GENERATED by ExternalStubPlugin — do not edit.",
    `// Re-exports of globalThis.${globalName} (set by the IIFE bundle).`,
    `const __external = /** @type {any} */ (globalThis).${globalName};`,
    "export const {",
    ...sorted.map((n) => `\t${n},`),
    "} = __external;",
    "",
  ].join("\n");
}

/**
 * Generates a thin "external" stub that re-exports the entries of a globally
 * assigned bundle (e.g. `self.$runtimekit`). Consumers that import the package
 * by its bare name pay zero source size — the stub is just a destructure of
 * the global.
 *
 * The export list is discovered automatically by parsing the already-emitted
 * bundle, so new exports flow through without any manual maintenance.
 */
class ExternalStubPlugin {
  bundleFilename: string;
  stubFilename: string;
  globalName: string;
  outputDir: string;

  constructor(opts: {
    bundleFilename: string;
    stubFilename: string;
    globalName: string;
    outputDir: string;
  }) {
    this.bundleFilename = opts.bundleFilename;
    this.stubFilename = opts.stubFilename;
    this.globalName = opts.globalName;
    this.outputDir = opts.outputDir;
  }

  apply(compiler: WebpackCompiler) {
    compiler.hooks.afterEmit.tap("ExternalStubPlugin", () => {
      const bundlePath = join(this.outputDir, this.bundleFilename);
      const stubPath = join(this.outputDir, this.stubFilename);
      let source: string;
      try {
        source = readFileSync(bundlePath, "utf-8");
      } catch (e: any) {
        console.error(
          `ExternalStubPlugin: cannot read ${bundlePath}: ${e.message}`,
        );
        return;
      }

      const names = extractRuntimeExportNames(source);
      if (names.length === 0) {
        console.warn(
          `ExternalStubPlugin: no exports discovered in ${bundlePath}; stub not written`,
        );
        return;
      }

      const stub = renderExternalStub(names, this.globalName);
      writeFileSync(stubPath, stub);
      console.log(
        `ExternalStubPlugin: wrote ${this.stubFilename} (${names.length} exports → globalThis.${this.globalName})`,
      );
    });
  }
}

// Custom plugin to generate TypeScript declarations
class TypeScriptDeclarationsPlugin {
  dir: string;
  tsconfigName: string;
  useAlias: boolean;
  tempDir: string;

  constructor(
    dir: string,
    tempDir: string,
    tsconfigName: string = "tsconfig.types.json",
    useAlias: boolean = true,
  ) {
    this.dir = dir;
    this.tempDir = tempDir;
    this.tsconfigName = tsconfigName;
    this.useAlias = useAlias;
  }

  apply(compiler: WebpackCompiler) {
    compiler.hooks.afterEmit.tap("TypeScriptDeclarationsPlugin", () => {
      (async () => {
        try {
          console.log(`Generating TypeScript declarations for ${this.dir}...`);
          try {
            const { stdout, stderr } = await execAsync(
              `corepack pnpm exec tsc --project ${this.tsconfigName}`,
              { cwd: this.dir },
            );
            if (stdout) console.log(stdout);
            if (stderr && !stderr.includes("TS")) console.error(stderr);
          } catch (tscError: any) {
            // tsc exits with error code if there are TS errors, but still generates files
            // Only log if it's not a TypeScript compilation error
            if (![1, 2].includes(tscError.code)) {
              throw tscError;
            }
            console.warn(
              `TypeScript declarations emitted with diagnostics for ${this.dir}`,
            );
            // if (tscError.stdout) console.log(tscError.stdout);
            // if (tscError.stderr) console.warn(tscError.stderr);
          }

          if (this.useAlias) {
            const aliasResult = await execAsync(
              `corepack pnpm exec tsc-alias --project ${this.tsconfigName}`,
              { cwd: this.dir },
            );
            if (aliasResult.stdout) console.log(aliasResult.stdout);
            if (aliasResult.stderr) console.error(aliasResult.stderr);
          }

          try {
            await execAsync(`rm -rf ${this.tempDir}`, { cwd: this.dir });
          } catch (e) {}

          console.log(
            `TypeScript declarations generated successfully for ${this.dir}`,
          );
        } catch (error: any) {
          console.error(
            `Error generating TypeScript declarations for ${this.dir}:`,
            error.message,
          );
        }
      })();
    });
  }
}

// Project directories
const runtimekitdir = join(__dirname, "packages/core");
const controllerdir = join(__dirname, "packages/controller");
const utilsdir = join(__dirname, "packages/utils");
const bootstrapdir = join(__dirname, "packages/bootstrap");

const wasmPath = join(runtimekitdir, "dist/runtimekit.wasm");
let wasmB64: string;
const wasmBuf = await readFile(wasmPath);
wasmB64 = wasmBuf.toString("base64");

export const tsloader = {
  test: /\.ts$/,
  loader: "builtin:swc-loader",
  exclude: ["/node_modules/"],
  options: {
    jsc: {
      parser: {
        syntax: "typescript",
      },
      target: "es2022",
    },
    module: {
      type: "es6",
      strict: false,
      strictMode: false,
    },
  },
  type: "javascript/auto",
};
//TODO: replace this
function deepmerge<T extends any>(target: T, source: Partial<T>): T {
  // this whole function is a hack, ignore all of the type errors
  //@ts-ignore this whole function is a hack
  const output = { ...target };
  if (isObject(target) && isObject(source)) {
    Object.keys(source).forEach((key) => {
      //@ts-ignore this whole function is a hack
      if (isObject(source[key])) {
        //@ts-ignore this whole function is a hack
        if (!(key in target)) Object.assign(output, { [key]: source[key] });
        //@ts-ignore this whole function is a hack
        else output[key] = deepmerge(target[key], source[key]);
      } else {
        //@ts-ignore this whole function is a hack
        Object.assign(output, { [key]: source[key] });
      }
    });
  }
  return output;
}

function isObject(item: any): item is Record<string, unknown> {
  return item && typeof item === "object" && !Array.isArray(item);
}
const rsDoctorPlugin =
  process.env.DEBUG === "1"
    ? new RsdoctorRspackPlugin({
        supports: {
          parseBundle: true,
          banner: true,
        },
      })
    : null;
class SanitizedSourceMapPlugin {
  apply(compiler: WebpackCompiler) {
    compiler.hooks.afterEmit.tap(
      "SanitizedSourceMapPlugin",
      (compilation: Compilation) => {
        const outputPath = compiler.options.output.path;
        if (!outputPath) return;
        for (const asset of Object.keys(compilation.assets)) {
          if (!asset.endsWith(".js")) continue;
          writeFileSync(
            join(outputPath, `${asset}.map`),
            JSON.stringify({
              version: 3,
              file: asset,
              sources: [],
              names: [],
              mappings: "",
            }),
          );
        }
      },
    );
  }
}

const createGenericConfig = (options: Partial<RspackOptions>) => {
  const def = {
    devtool: false,
    mode: "development" as Mode,
    resolve: {
      extensions: [".ts", ".js"],
    },
    module: {
      rules: [tsloader],
      parser: {
        javascript: {
          overrideStrict: "non-strict",
          dynamicImportMode: "eager",
        },
      },
    },
    optimization: {
      minimizer: [
        new rspack.SwcJsMinimizerRspackPlugin({
          minimizerOptions: {
            module: options.output?.libraryTarget === "module",
          },
        }),
      ],
    },
  };
  const merged = deepmerge<RspackOptions>(
    def as unknown as RspackOptions,
    options,
  );
  merged.plugins = [
    ...(merged.plugins || []),
    ...(rsDoctorPlugin ? [rsDoctorPlugin] : []),
    new SanitizedSourceMapPlugin(),
  ];
  return defineConfig(merged);
};

type RuntimeKitBuildConfig = {
  entry: RspackOptions["entry"];
  output: RspackOptions["output"];
  rewriterWasm: string;
  extraConfig?: Partial<RspackOptions>;
  name: string;
};
// Common configuration options for runtimekit builds
const createRuntimeKitConfig = (options: RuntimeKitBuildConfig) => {
  const { entry, output, rewriterWasm, extraConfig = {}, name } = options;

  return createGenericConfig({
    name,
    entry,
    resolve: {
      alias: {
        "@rewriters": join(runtimekitdir, "src/shared/rewriters"),
        "@client": join(runtimekitdir, "src/client"),
        "@": join(runtimekitdir, "src"),
      },
    },
    output,
    plugins: [
      // new TsCheckerRspackPlugin({
      // 	typescript: {
      // 		configFile: resolve(runtimekitdir, "tsconfig.json"),
      // 	},
      // }),
      new rspack.ProvidePlugin({
        dbg: [join(runtimekitdir, "src/log.ts"), "default"],
      }),
      new rspack.DefinePlugin({
        REWRITERWASM: rewriterWasm,
      }),
      new rspack.DefinePlugin({
        VERSION: JSON.stringify(sjpackagemeta.version),
      }),
      new rspack.DefinePlugin({
        COMMITHASH: (() => {
          try {
            const hash = JSON.stringify(
              execSync("git rev-parse --short HEAD", {
                encoding: "utf-8",
              }).replace(/\r?\n|\r/g, ""),
            );

            return hash;
          } catch {
            return JSON.stringify("unknown");
          }
        })(),
      }),
      new rspack.DefinePlugin({
        BUILDDATE: JSON.stringify(new Date().toISOString()),
      }),
    ],
    target: "webworker",
    ignoreWarnings: [
      {
        module: /src\/entry\.ts/,
        message:
          /Critical dependency: the request of a dependency is an expression/,
      },
    ],
    ...extraConfig,
  });
};

const sjpackagemeta = JSON.parse(
  await readFile(join(runtimekitdir, "package.json"), "utf-8"),
);
// IIFE build that does NOT bundle the wasm, exposes global $runtimekit
const iifeConfig = createRuntimeKitConfig({
  name: "runtimekit-iife",
  entry: {
    main: join(runtimekitdir, "src/index.ts"),
  },
  output: {
    filename: "runtimekit.js",
    path: join(runtimekitdir, "dist"),
    iife: true,
    library: {
      type: "assign",
      name: "self.$runtimekit",
    },
  },
  rewriterWasm: "undefined",
  extraConfig: {
    performance: {
      hints: false,
    },
  },
});

// IIFE build that BUNDLES the wasm and exposes global $runtimekit
const iifeBundledConfig = createRuntimeKitConfig({
  name: "runtimekit-iife-bundled",
  entry: {
    bundled: join(runtimekitdir, "src/index.ts"),
  },
  output: {
    filename: "runtimekit_bundled.js",
    path: join(runtimekitdir, "dist"),
    iife: true,
    library: {
      type: "assign",
      name: "self.$runtimekit",
    },
  },
  rewriterWasm: JSON.stringify(wasmB64),
  extraConfig: {
    performance: {
      hints: false,
    },
  },
});

// no wasm bundled, esmodule
const moduleConfig = createRuntimeKitConfig({
  name: "runtimekit-esmodule",
  entry: {
    bundle: join(runtimekitdir, "src/index.ts"),
  },
  output: {
    filename: "runtimekit.mjs",
    path: join(runtimekitdir, "dist"),
    libraryTarget: "module",
    iife: false,
  },
  // do not embed the wasm in this build
  rewriterWasm: "undefined",
  extraConfig: {
    performance: {
      hints: false,
    },
    experiments: {
      outputModule: true,
    },
  },
});
moduleConfig.plugins!.push(
  new ExternalStubPlugin({
    bundleFilename: "runtimekit.mjs",
    stubFilename: "runtimekit-external.mjs",
    globalName: "$runtimekit",
    outputDir: join(runtimekitdir, "dist"),
  }),
);

// wasm bundled, esmodule
const moduleBundledConfig = createRuntimeKitConfig({
  name: "runtimekit-esmodule-bundled",
  entry: {
    bundle: join(runtimekitdir, "src/index.ts"),
  },
  output: {
    filename: "runtimekit_bundled.mjs",
    path: join(runtimekitdir, "dist"),
    libraryTarget: "module",
    iife: false,
  },
  rewriterWasm: JSON.stringify(wasmB64),
  extraConfig: {
    performance: {
      hints: false,
    },
    experiments: {
      outputModule: true,
    },
  },
});

// Type generation configuration
const typeGenConfig = defineConfig({
  context: runtimekitdir,
  entry: {
    index: "./src/index.ts",
  },
  output: {
    path: join(runtimekitdir, "dist/temp-types-build"),
    filename: "[name].js",
  },
  plugins: [
    new TypeScriptDeclarationsPlugin(
      runtimekitdir,
      "dist/temp-types-build",
      "tsconfig.types.json",
      true,
    ),
  ],
  resolve: {
    extensions: [".ts", ".js"],
    alias: {
      "@rewriters": join(runtimekitdir, "src/shared/rewriters"),
      "@client": join(runtimekitdir, "src/client"),
      "@": join(runtimekitdir, "src"),
    },
  },
  module: {
    rules: [tsloader],
  },
});

// Load WASM for rewriter
const controllermeta = JSON.parse(
  await readFile(join(controllerdir, "package.json"), "utf-8"),
);
const controllerVersionDefines = new rspack.DefinePlugin({
  RUNTIMEKIT_EXPECTED_VERSION: JSON.stringify(sjpackagemeta.version),
  CONTROLLER_VERSION: JSON.stringify(controllermeta.version),
});

const controllerConfig = createGenericConfig({
  name: "runtimekit-controller",
  dependencies: ["runtimekit-esmodule"],
  entry: {
    api: join(controllerdir, "src/index.ts"),
    inject: join(controllerdir, "src/inject.ts"),
    sw: join(controllerdir, "src/sw.ts"),
  },
  output: {
    filename: "controller.[name].js",
    path: join(controllerdir, "dist"),
    iife: true,
    library: {
      type: "var",
      name: "$runtimekitController",
    },
  },
  target: "web",
  plugins: [
    controllerVersionDefines,
    new ExternalStubPlugin({
      bundleFilename: "controller.api.js",
      stubFilename: "controller-external.mjs",
      globalName: "$runtimekitController",
      outputDir: join(controllerdir, "dist"),
    }),
    new TypeScriptDeclarationsPlugin(
      controllerdir,
      "dist/temp-types-build",
      "tsconfig.types.json",
      false,
    ),
  ],
});

const utilsVersionDefines = new rspack.DefinePlugin({
  RUNTIMEKIT_EXPECTED_VERSION: JSON.stringify(sjpackagemeta.version),
  CONTROLLER_EXPECTED_VERSION: JSON.stringify(controllermeta.version),
});

const utilsIifeConfig = createGenericConfig({
  name: "runtimekit-utils-iife",
  dependencies: ["runtimekit-esmodule", "runtimekit-controller"],
  entry: {
    main: join(utilsdir, "src/index.ts"),
  },
  output: {
    filename: "runtimekit-utils.js",
    path: join(utilsdir, "dist"),
    iife: true,
    library: {
      type: "assign",
      name: "self.$runtimekitUtils",
    },
  },
  target: "web",
  plugins: [
    utilsVersionDefines,
    new TypeScriptDeclarationsPlugin(
      utilsdir,
      "dist/temp-types-build",
      "tsconfig.types.json",
      false,
    ),
  ],
});

const utilsModuleConfig = createGenericConfig({
  name: "runtimekit-utils-esmodule",
  dependencies: ["runtimekit-esmodule", "runtimekit-controller"],
  entry: {
    main: join(utilsdir, "src/index.ts"),
  },
  output: {
    filename: "runtimekit-utils.mjs",
    path: join(utilsdir, "dist"),
    libraryTarget: "module",
    iife: false,
  },
  experiments: {
    outputModule: true,
  },
  target: "web",
  plugins: [
    utilsVersionDefines,
    new TypeScriptDeclarationsPlugin(
      utilsdir,
      "dist/temp-types-build",
      "tsconfig.types.json",
      false,
    ),
  ],
});

const bootstrapConfig = createGenericConfig({
  name: "runtimekit-bootstrap",
  entry: {
    server: join(bootstrapdir, "src/server.ts"),
    client: join(bootstrapdir, "src/client.ts"),
  },
  output: {
    filename: "bootstrap-[name].js",
    path: join(bootstrapdir, "dist"),
    iife: false,
    libraryTarget: "module",
  },
  experiments: {
    outputModule: true,
  },
  target: "node",
  externals: [nodeExternals],
  module: {
    parser: {
      javascript: {
        importMeta: false,
      },
    },
  },
  plugins: [
    new TypeScriptDeclarationsPlugin(
      bootstrapdir,
      "dist/temp-types-build",
      "tsconfig.types.json",
      false,
    ),
  ],
});

const bootstrapStaticConfig = createGenericConfig({
  name: "runtimekit-bootstrap-static",
  entry: {
    static: join(bootstrapdir, "src/static.ts"),
  },
  output: {
    filename: "bootstrap-[name].js",
    path: join(bootstrapdir, "dist"),
    iife: true,
  },
});

export default [
  iifeConfig,
  iifeBundledConfig,
  moduleConfig,
  moduleBundledConfig,
  typeGenConfig,
  controllerConfig,
  utilsIifeConfig,
  utilsModuleConfig,
  bootstrapConfig,
  bootstrapStaticConfig,
];
